// Code generated by reset. DO NOT EDIT.
package reset

func (t *TestResetableStruct) Reset() {
	if t == nil {
		return
	}

	t.ID = 0
	t.Name = ""
	t.Data = t.Data[:0]
	t.Items = t.Items[:0]
}
func (a *AnotherResetableStruct) Reset() {
	if a == nil {
		return
	}

	a.Counter = 0
	a.Active = false
	a.Values = a.Values[:0]
	clear(a.Config)
}
